version: '3.8'

services:
  infopulse-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infopulse-app
    expose:
      - "3000"  # внутренний порт, который слушает ваше приложение
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=app.example.com
      - LETSENCRYPT_HOST=app.example.com
      - LETSENCRYPT_EMAIL=you@example.com
      - VIRTUAL_PORT=3000  # порт внутри контейнера, который слушает приложение
    volumes:
      - ./:/app
      - infopulse_node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - web

  infopulse-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: infopulse-dev
    expose:
      - "5173"
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=dev.app.example.com
      - LETSENCRYPT_HOST=dev.app.example.com
      - LETSENCRYPT_EMAIL=you@example.com
      - VIRTUAL_PORT=5173
    volumes:
      - ./:/app
      - infopulse_node_modules:/app/node_modules
    command: npm run dev
    profiles:
      - dev
    networks:
      - web

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
    networks:
      - web

volumes:
  infopulse_node_modules:

networks:
  web:
    driver: bridge